### ISSUE TITLE
[BUG] Cannot access RSP Portal or Notebooks aspects

### ISSUE THREAD

**Issue by yymao** [rubin-dp0/Support#1]
**Describe the bug**
I can successfully log in to [RSP](https://data.lsst.cloud/) using my GitHub account (@yymao; I'm already in the [`rubin-dp0/delegates` team](https://github.com/orgs/rubin-dp0/teams/delegates/members?query=yymao)). However, when I click on "Portal" I just got a blank page with "403 Forbidden". When I click on "Notebooks", I got a text error message saying: `{"detail":{"msg":"Token missing required scope","type":"permission_denied"}}`

**To Reproduce**
1. Go to [RSP](https://data.lsst.cloud/) and log in
2. Click on [Portal](https://data.lsst.cloud/portal/app/) or [Notebooks](https://data.lsst.cloud/nb)
3. See errors

**Expected behavior**
I expect being able to access Portal and Notebooks aspects. 

**Screenshots**

For [Portal](https://data.lsst.cloud/portal/app/) 
![image](https://user-images.githubusercontent.com/3792659/124060124-5a010600-d9fa-11eb-8e2c-08515566f23d.png)

For [Notebooks](https://data.lsst.cloud/nb)
![image](https://user-images.githubusercontent.com/3792659/124060147-69804f00-d9fa-11eb-9b92-452198585ea8.png)

**URL**
- https://data.lsst.cloud/portal/app/
- https://data.lsst.cloud/nb

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 / Kernel 5.11
 - Browser: Google Chrome
 - Version: 91

But the issue seems to be independent of browser/OS

**Additional context**

I know @katrinheitmann is experiencing the same issue as of June 30, 11pm EDT.

**Comment by frossie** [comment]
Thanks for the report. Could you please try logging out of Github and logging back in again and let us know whether that helps.

**Comment by yymao** [comment]
I have also tried logging out of GitHub completely and log in again, but the issue persists.

**Comment by frossie** [comment]
Okay we are investigating thanks.

**Comment by frossie** [comment]
Did you get a pop-up from Github asking you to authorize the RSP to access your account?

**Comment by katrinheitmann** [comment]
yes, I got one (and then an email from github confirming that I allowed accesss)

**Comment by sidneymau** [comment]
I am just commenting to note that I am seeing the same behavior as Yao posted. I accepted the GitHub popup authorizing RSP to use my account and have tried logging out and back in.

**Comment by yymao** [comment]
Re: @frossie 

> Did you get a pop-up from Github asking you to authorize the RSP to access your account?

Yes I did when I logged in for the first time.

**Comment by athornton** [comment]
Team-to-scope mapping appears correct in Gafaelfawr.  

```
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
        - "lsst-ops"
        - "rubin-dp0-delegates"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
        - "lsst-ops"
        - "rubin-dp0-delegates"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
        - "lsst-ops"
        - "rubin-dp0-delegates"
```

ought to be granting the correct permissions to `rubin-dp0-delegates` members.

**Comment by frossie** [comment]
Alright thank you for your patience. If you have NOT yet tripped this error, I believe we should have fixed the issue, which was due to a Github Organisation security setting that was not the default behaviour when we have tested this previous. 

Next reply I will explain what to do for those of you who have unfortunately already tripped this.

**Comment by frossie** [comment]
If you have already run into the problem described, here is how to recover:

1. Go to data.lsst.cloud and from the top right menu item that has your username log out

<img width="244" alt="Screenshot of Safari (2021-06-30, 21-11-33)" src="https://user-images.githubusercontent.com/1933621/124063459-c6bed500-d9e7-11eb-8e24-c92e38bbd812.png">

2. Go to https://github.com/settings/applications (or if you want to navigate, go to your Github account's settings -> Applications -> Authorized OAuth Apps **TAB** ) and find the RSP entry and hit REVOKE on the little menu:

<img width="898" alt="Screenshot of Safari (2021-06-30, 21-15-46)" src="https://user-images.githubusercontent.com/1933621/124063725-60868200-d9e8-11eb-9558-6dec390be546.png">

3. Go back to data.lsst.cloud and log in. 

4. You should (a) get the Github popup asking you to authorize the application and (b) it should have a green tick next to dp-0 (and nothing else - specifically not a button saying "Grant") 

<img width="151" alt="Screenshot of Slack (2021-06-30, 21-17-15)" src="https://user-images.githubusercontent.com/1933621/124063909-b0654900-d9e8-11eb-894c-f94321f96416.png">

And please kindly report back even if it works!

**Comment by sidneymau** [comment]
I can confirm following [these steps](https://github.com/rubin-dp0/Support/issues/1#issuecomment-871904198) fixed the issue for me!

**Comment by katrinheitmann** [comment]
Same here, thanks very much!

**Comment by frossie** [comment]
Fantastic. Thank you for being early adopters and sorry for not catching this particular issue in testing. 

In the future we will add code to our logout function to clear out the Github Oauth grant, so that if the process fails for some reason we will not have to talk users out of the Revoke step ahead, which is quite gnarly.

**Comment by frossie** [comment]
@yymao when you confirm it works for you, I will close the ticket.

**Comment by yymao** [comment]
Thank you @frossie. But unfortunately I still encounter the same issue after following your steps.  After revoking the RSP entry, I was indeed prompted to grant permission when I logged in again to RSP:

![image](https://user-images.githubusercontent.com/3792659/124118205-141a6100-da3f-11eb-804d-b4718bec832c.png)

But then I still cannot access Portal or Notebooks (same error messages as in my original post).

**Comment by pothiers** [comment]
The instructions (revoke and retry) did NOT work for me.  I tried twice just in case. I get the 403 Forbidden error described in initial post.

**Comment by pothiers** [comment]
I'm suspicious that something about my email change (noao to noirlab) might be involved.  I've gotten two GitHub OAuth emails about RSP.  One to my personal gmail account used for my github account before joining noao, and one to my new  noirlab.edu email.

**Comment by frossie** [comment]
@pothiers your problem is you are not on the delegate list whitelisted for science platform access in DP0.1 -  I will inquire with the CET team your access status.

**Comment by frossie** [comment]
@yymao @jchiang87 we are working your issue - sorry for the delay

**Comment by frossie** [comment]
Okay the problem the remaining users are having (including @yymao ) is that you are all members of so many Github teams, the Github API is paginating the results and Rubin is not on the first page. Instead of trying to talk you through a work around, we are going to get the auth code fixed to deal with paginated results and roll it out, and then we have actually fixed something which is the whole point of this exercise. Sorry about that, you should be good by tomorrow.

**Comment by MelissaGraham** [comment]
@frossie, @pothiers is on the Friends team

**Comment by yymao** [comment]
Thank you for the update @frossie. Indeed I'm in 12 different GitHub Organizations now... :slightly_smiling_face:

**Comment by frossie** [comment]
@yymao  Yes the issue is the number of teams (not just orgs) and lsstdesc seems to have... 130 of them... and I bet you're on more than one ... Thanks for being a good test user :-)

**Comment by frossie** [comment]
Ok @yymao has kindly helped us test the new authentication code. Yao and everyone else having a remaining problem: please follow [the instructions above](https://github.com/rubin-dp0/Support/issues/1#issuecomment-871904198) and  report outcome.

**Comment by yymao** [comment]
Thank you @frossie -- I can confirm that both Portal and Notebooks work for me now on  https://data.lsst.cloud/ after following your steps above!

**Comment by frossie** [comment]
Thank you so much for testing with us @yymao and thanks @rra for the quick turnaround on the fix.

**Comment by pothiers** [comment]
@frossie Now works for me too.  Thanks for the fix and for avoiding the temptation for doing a work-around!

**Comment by frossie** [comment]
@pothiers ah yes, fyi Steve for the record your  login is working because @MelissaGraham authorised me to add the dp0 friends team to the allow list. I think that brings us to 5 different root causes in one issue :-)

**Comment by jchiang87** [comment]
Hi Everyone,  I confirm that I can now open a jupyter notebook and access the portal after following the steps above.

**Comment by fklich** [comment]
hello troubleshooters.
Yesterday, after the DP0 session with Melissa, I tested my access to the Portal and NB and they presented just fine.
This morning I am having exact same problem as described above.  I have repeated the above steps twice with no success.

**Comment by frossie** [comment]
@fklich I am sorry, I don't know who you are. You are not on the delegate list I was given. Under which umbrella are you expecting access - Rubin staff, DP0.1 delegate, CET collaborator... ?

**Comment by MelissaGraham** [comment]
I sent @fklich a direct message in the Community Forum to resolve this.

**Comment by fklich** [comment]
Thanks Frossie.  I read Melissa's direct message and your question and understand the situation.  Ticket CLOSED!!
Happy 4th.
Fred Klich
________________________________

**Comment by ashruiter** [comment]
Yes this worked for me - thank you!

**Comment by frossie** [comment]
For anyone who stumbles on this ticket in the future: We have simplified the process by which you can now recover from this type of error. New users (after 2021-07-09) will be able to clear existing tokens just by logging out, greatly simplifying the process outlined above. See https://community.lsst.org/t/rsp-data-lsst-cloud-updates-2021-07-09/5633
