### ISSUE TITLE
[BUG] 500 Internal Server Error - I can not access RSP Notebooks or Portal 

### ISSUE THREAD

**Issue by MartaFatovic** [rubin-dp0/Support#10]
**Describe the bug**

When I (successfully) log in to RSP and click on Notebooks or Portal, I get the same "500 Internal Server Error" message. I am also in the rubin-dp0/delegates team. I also tried to fix it like this ( https://github.com/rubin-dp0/Support/issues/1#issuecomment-871904198 ) but this did not work for me.

**To Reproduce**
1. Go to Rubin Science Platform (https://data.lsst.cloud/) and log in (while logged in my GitHub account - MartaFatovic)
2. Click on Portal or Notebooks
4. See error: "500 Internal Server Error " 

**Expected behavior**
Access Notebooks and Portal.

**Screenshots**

![500 Internal Server Error](https://user-images.githubusercontent.com/73060328/124991231-ac1cd980-e041-11eb-8b4a-821273911ba3.png)

**URL**
https://data.lsst.cloud/portal/app/

https://data.lsst.cloud/nb

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Mozilla Firefox 89.0.2

**Comment by frossie** [comment]
Okay thanks for the report and sorry for the trouble. We seem to have a unicode bug somewhere in the software chain that's being tripped by your username. I have triaged this at high priority and we're looking at rolling out a hotfix.

**Comment by frossie** [comment]
Okay, we hope to deploy a fix into production tomorrow. Sorry for the delay and thank you for being a good test case (which we should have anticipated).

**Comment by frossie** [comment]
Sorry about that Marta, can you log out (if you are still logged in) and log back in again and tell us if that's better now?

**Comment by MartaFatovic** [comment]
It works now! Thank you very much!

**Comment by frossie** [comment]
Great thanks for letting us know and sorry for the trouble. Besides the fix we now have a suite of unit tests to detect such issues in the future.
