### ISSUE TITLE
[BUG] Communications link failure when running query

### ISSUE THREAD

**Issue by MichelleLochner** [rubin-dp0/Support#11]
**Describe the bug**
I noticed that queries were running much slower today compared to yesterday. I tried running the same query on the portal and in the intro notebook and I got the following error:

```
Table Load Error:
Communications link failure

The last packet successfully received from the server was 610,191 milliseconds ago.  The last packet sent successfully to the server was 610,192 milliseconds ago. Communications link failure

The last packet successfully received from the server was 610,191 milliseconds ago.  The last packet sent successfully to the server was 610,192 milliseconds ago. Connection timed out (Read failed)
```

**To Reproduce**
1. Run the following query in the intro notebook:
```
results = service.search("SELECT ra, dec, mag_g, mag_r, mag_i "\
                         "FROM dp01_dc2_catalogs.object "\
                         "WHERE CONTAINS(POINT('ICRS', ra, dec), CIRCLE('ICRS', 62.0, -37.0, 0.5)) = 1 ", maxrec=10)
```

**Expected behavior**
Query to run

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 91.0.4472.77

**Comment by fritzm** [comment]
Hi @MichelleLochner -- thank you for the report!

We are currently seeing some instability in the Qserv cluster which is supporting TAP queries.  The issue is being investigated and we'll post more information here for you when we have it.

**Comment by frossie** [comment]
Consolidating under https://github.com/rubin-dp0/Support/issues/14 - please subscribe to that for updates.
