### ISSUE TITLE
[BUG] incorrect typing causes incorrect sorting

### ISSUE THREAD

**Issue by RoyWilliams** [rubin-dp0/Support#12]
**Describe the bug**
Subtracting two double's should be a double not a char

**To Reproduce**
1. Go to Firefly portal
2. Choose TAP service = RSP
3. Choose ADQL
4. Enter this query and click Search
    SELECT mag_g,mag_r, mag_g-mag_r as color
    FROM dp01_dc2_catalogs.object 
    WHERE CONTAINS(POINT('ICRS', ra, dec),CIRCLE('ICRS', 55, -35, 1))=1 
    AND (mag_g <21 AND mag_r <21)

**Expected behavior**
If I click on the sort button in the display, it should sort as doubles, not as chars

**Actual behavior** 
Seems strange that "color" is a char field. 
If I click on the sort button in the display it sorts alphabetically instead of numerically
![mag_g-mag_r](https://user-images.githubusercontent.com/8886481/125261149-e82d9400-e2f8-11eb-84f2-8a2f0e1b5058.png)

** Additional context **
However, if I add "ORDER BY color DESC" to my ADQL, then the sorting is correct.

**Comment by frossie** [comment]
Thanks for the report, we are investigating which is the offending layer of the sandwich

**Comment by fritzm** [comment]
Verified that Qserv is returning correctly typed result data to TAP for this query.

**Comment by frossie** [comment]
We have rolled out a fix to this. @RoyWilliams please give it a try.

**Comment by RoyWilliams** [comment]
Looks great! Thank you!

**Comment by frossie** [comment]
For the record, fix upstreamed to CADC, h/t @cbanek
