### ISSUE TITLE
[BUG] Portal query does not complete

### ISSUE THREAD

**Issue by nsabrams** [rubin-dp0/Support#13]
**Describe the bug**
Portal query does not complete

**To Reproduce**
1. Go to the portal
2. Search for M81 with a search radius of 1 arcsec
3. Click search

**Expected behavior**
The query should finish, with no results because m81 is not in the field of view of DP0

**Screenshots**
Here's the query I input:
![image](https://user-images.githubusercontent.com/31581144/125335877-0f955880-e31b-11eb-8764-33d3082e196d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by fritzm** [comment]
Hi @nsabrams -- thanks for the report!

We are currently experiencing some difficulty with Qserv which is impacting many users' queries.  This may result in abnormally long query execution times, such as you have noted here.

The team is actively pursuing a fix for this right now, and we will keep you all updated here and on other reported issues.  In the meantime we are manually intervening on the server to keep query processing moving along.  Unfortunately, the best advice I can offer at this time when encountering a "stuck" query is to retry after a few minutes.

Thank you for your patience while we work out this bump -- we hope to have smooth query service restored for all of you soon.

**Comment by frossie** [comment]
Consolidating under https://github.com/rubin-dp0/Support/issues/14 - please subscribe to that for updates.
