### ISSUE TITLE
[BUG] Intermittent lock-up of Qserv query processing

### ISSUE THREAD

**Issue by fritzm** [rubin-dp0/Support#14]
Qserv query processing sometimes locks up, requiring manual intervention by a server operator to be "unstuck".

This has been reported as #11 and #13, and also variously in the Community support forum and on Slack.  This ticket is intended to provide a place to accumulate information on further occurrences and for consolidated tracking of progress on the underlying issue.

**Comment by frossie** [comment]
For a longer explanation of this issue see https://community.lsst.org/t/intermittent-qserv-tap-query-service-issue-2021-07-13/5653

**Comment by ktlim** [comment]
Qserv got stuck on a `SELECT * FROM object` query just now.  I restarted.

It appeared that there were a few other queries that were also stuck, including an `object`/`truth_match` join.

**Comment by fritzm** [comment]
Okay, we believe this to be fixed with deployment of Qserv release 2021.7.1-rc1 this past Friday.  The root cause was a resource deadlock in query distribution and result-accumulation code, at the interface between the Qserv head node and the underlying XRootD messaging/streaming library.  Thank you for your patience while we tracked this one down!
