### ISSUE TITLE
Attribute does not exist in Tutorial 03

### ISSUE THREAD

**Issue by astrobatty** [rubin-dp0/Support#15]
In ``03_Image_Display_and_Manipulation.ipynb`` there is a comment line which says

```python
# Note that the keys are slightly different for DC2/LSSTCam
# You can view all the keys by creating the butler and calling:
#   print(butler.getKeys('calexp'))"
```

but there is no ``.getKeys`` attribute in Butler. This comment should be removed from the tutorial.

**Comment by MelissaGraham** [comment]
Added fixing this to the open Jira ticket to address NB 03 issues: https://jira.lsstcorp.org/browse/PREOPS-583

**Comment by MelissaGraham** [comment]
@gpdf you're right, this got fixed and PREOPS-583 was marked as done, so this issue can be closed.
