### ISSUE TITLE
Access to data.lsst.cloud

### ISSUE THREAD

**Issue by fklich** [rubin-dp0/Support#18]
I have GitHub account for years, user id klich
I am a member of the LSST Community Forum, and prior LSST Community Forum Workshops.
Is access to the data.lsst.cloud Portal, Notebooks and API's limited at this time?
Please advise;  contact info in my Github profile.
Fred klich, Dallas Tx

**Comment by MelissaGraham** [comment]
Noting connection with issue #2: 
https://github.com/rubin-dp0/Support/issues/2#issuecomment-873126112

Closing issue.

**Comment by fklich** [comment]
Melissa, 
  Thanks for the reply.  I will offer a reply in a couple days, as I am another astronomy adventure now with UNT in the Rockies.
  Fred , Dallas
