### ISSUE TITLE
Unable to access Portal or Notebooks at data.lsst.cloud

### ISSUE THREAD

**Issue by fklich** [rubin-dp0/Support#2]
Describe the bug
Yesterday evening after the dp0 session with Melissa I did successfully log into data.lsst.cloud and also checked access to Portal and Notebooks and API which worked fine.
This morning, it stopped working with same issue as reported below by @yymao with my account = fklich 
=====================================================================
**I can successfully log in to RSP using my GitHub account (@yymao; I'm already in the rubin-dp0/delegates team). However, when I click on "Portal" I just got a blank page with "403 Forbidden". When I click on "Notebooks", I got a text error message saying: {"detail":{"msg":"Token missing required scope","type":"permission_denied"}}**Describe the bug****
=====================================================================
I repeated the recommended steps twice with no success.
One additional factor.  I am unable to pull up the list of "rubin-dp0/delegates team", so not sure if something changed in that respect since yesterday .......

**Comment by MelissaGraham** [comment]
Hi Fred, thanks for submitting a GitHub Issue -- I reached out to you via direct message in the Community Forum at Community.lsst.org before seeing this one, so I'm going to close the issue.
