### ISSUE TITLE
[BUG]  cannot import name "median_abs_deviation" from "scipy.stats" in 05_Intro_to_Source_Detection.ipynb

### ISSUE THREAD

**Issue by ryanhausen** [rubin-dp0/Support#21]
**Describe the bug**
When you try to run the cell that includes:

`from lsst.pipe.tasks.characterizeImage import CharacterizeImageTask`

there is an import error: " cannot import name "median_abs_deviation" from "scipy.stats" "

**To Reproduce**
1. Go to 05_Intro_to_Source_Detection.ipynb
2. Run the cell with the lsst imports

**Expected behavior**
Import modules

**Comment by timj** [comment]
Which pipelines weekly version are you running?

**Comment by MelissaGraham** [comment]
@ryanhausen I'm sorry this didn't occur to me today in Stack Club, but try this troubleshooting tip: https://dp0-1.lsst.io/data-access-analysis-tools/index-nb-intro.html#how-to-recover-from-package-import-errors-importerror

Let us know if that's the right fix for that issue?

**Comment by ryanhausen** [comment]
@timj @MelissaGraham 

Thanks for the prompt reply, the troubleshooting tips fixed it, must be an issue with my .local

Thanks!
