### ISSUE TITLE
Cannot login to Rubin Science Platform

### ISSUE THREAD

**Issue by ethlau** [rubin-dp0/Support#22]
Cannot login to the  Rubin Science Platform

In particular, I got the following error message: 

```
Authentication error
Authentication failed with the following error:

Error: User unauthorized: ethlau is not a member of any authorized groups

To report problems or ask for help, please open an issue in the GitHub rubin-dp0/Support project.
```

**Comment by frossie** [comment]
Hi, are you a member of the Data Preview 0 delegate program? If so can you tell me when you received your invitation?

**Comment by MelissaGraham** [comment]
Hi Erwin,

At the moment, access to the Rubin Science Platform (RSP) at data.lsst.cloud is limited to the 300 people who applied to participate in Data Preview 0 (DP0) earlier this year. I don't see an application from you, but we're very happy to hear that you're interested. The next round of applications for Phase 2 of DP0 will be March-April 2022, and new RSP accounts will be set up by June 30 2022. The best way to ensure that you're informed when that application form opens is to join the Rubin Science Mailing List, which you can do using the Subscribe button in the left menu bar at https://www.lsst.org/scientists.

If you have any more questions about Rubin's DP0 or the RSP, please feel free to reply in this thread or visit the Rubin Community Forum at Community.lsst.org.

Melissa Graham
