### ISSUE TITLE
Tap service not working in tutorial notebooks

### ISSUE THREAD

**Issue by ledwar04** [rubin-dp0/Support#23]
I am trying to start the TAP service, following the steps on the tutorials (eg tutorial 1):
service = get_tap_service()

But, I keep getting an error, when I run the tutorials, and also when I run my own notebooks (that used to work). 

To reproduce the error, try running tutorial number one, and it will happen at this command:
service = get_tap_service()

**Expected behavior**
There should be no error (and no output).

**Screenshots**
I don't know how to insert a screenshot here. However, this is the error I get (in bold):

**---------------------------------------------------------------------------
DALServiceError                           Traceback (most recent call last)
/tmp/ipykernel_36394/1920553455.py in <module>
----> 1 service = get_tap_service()

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/lsst/rsp/catalog.py in get_tap_service()
     36 
     37 def get_tap_service() -> pyvo.dal.TAPService:
---> 38     return pyvo.dal.TAPService(_get_tap_url(), _get_auth())
     39 
     40 

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/pyvo/dal/tap.py in __init__(self, baseurl, session)
    118         # One such usecase for this is auth.
    119         if hasattr(self._session, 'update_from_capabilities'):
--> 120             self._session.update_from_capabilities(self.capabilities)
    121 
    122     @property

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    765                     val = obj_dict.get(self._key, _NotFound)
    766                     if val is _NotFound:
--> 767                         val = self.fget(obj)
    768                         obj_dict[self._key] = val
    769             return val

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/pyvo/dal/vosi.py in capabilities(self)
     90     @lazyproperty
     91     def capabilities(self):
---> 92         return vosi.parse_capabilities(self._capabilities().read)
     93 
     94 

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/pyvo/utils/decorators.py in wrapper(*args, **kwargs)
      8     @wraps(func)
      9     def wrapper(*args, **kwargs):
---> 10         raw = func(*args, **kwargs)
     11         raw.read = partial(raw.read, decode_content=True)
     12         return raw

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/pyvo/dal/vosi.py in _capabilities(self)
     86         py:class:`~pyvo.io.vosi.availability.Availability` object
     87         """
---> 88         return self._get_endpoint('capabilities')
     89 
     90     @lazyproperty

/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages/pyvo/dal/vosi.py in _get_endpoint(self, endpoint)
     38                 continue
     39         else:
---> 40             raise DALServiceError(
     41                 "No working {endpoint} endpoint provided".format(
     42                     endpoint=endpoint))

DALServiceError: No working capabilities endpoint provided**

**Desktop (please complete the following information):**
 I'm running on Mac OS Big Sur 11.6.1, Chrome

**Comment by frossie** [comment]
Hi, can you perform the following steps and let me know if it still happens?

1. Exit from the Notebook menu (Files->Exit without saving or Save and Exit)
2. Log out from the home page (data.lsst.cloud top right menu)
3. Start again, making sure you selected the Recommended image

and let us know what happens?

Screenshot for step 1:

<img width="295" alt="Screenshot of Safari (2022-01-11, 19-57-03)" src="https://user-images.githubusercontent.com/1933621/149055912-d3c9c4c5-f50d-41cf-aaa1-85c36ed7f25b.png">


Screenshot for step 2:

<img width="274" alt="Screenshot of Safari (2022-01-11, 11-02-29)" src="https://user-images.githubusercontent.com/1933621/149055763-173ccdbd-2227-4e36-b6f2-fe1d4a2a2b5b.png">

Screenshot for step 3:


<img width="682" alt="Screenshot of Safari (2022-01-11, 19-58-50)" src="https://user-images.githubusercontent.com/1933621/149056048-b2c64a48-1f28-4f39-9f70-095002ad6fe6.png">

**Comment by frossie** [comment]
@ledwar04 did that help?

**Comment by ledwar04** [comment]
Yes! That helped, thanks!
