### ISSUE TITLE
[BUG] Column constraints in RSP TAP

### ISSUE THREAD

**Issue by igorandreoni** [rubin-dp0/Support#26]
In the RSP TAP online service, the table constraints inserted manually get applied to the wrong column, at least in the case of "cModel" columns.

**To Reproduce**
1. Go to 'RSP TAP Search'
2. Insert coordinates (e.g. "61.863 -35.79")
3. Insert column constraint (bottom right, e.g. mag_z_cModel < 20, see screenshot 1)
4. See the query results, or the ADQL query by clicking "Populate and edit ADQL"
5. The constraints are applied to the wrong column (see screenshot 2)6. 

Note that this problem does **not** occur, for example, for columns including "ra", "mag_i", "mag_z".

**Expected behavior**
I would expect that, if I set a constraint on the column mag_z_cModel, this results in a WHERE condition (and query results) that concern the column of interest.

**Screenshots**
Constraint that I set
<img width="1255" alt="Screen Shot 2022-04-14 at 9 15 10 AM" src="https://user-images.githubusercontent.com/22763282/163399301-f3b059c1-cd88-40ba-9a2b-08a01e118d1c.png">

Resulting ADQL query
<img width="1240" alt="Screen Shot 2022-04-14 at 9 15 22 AM" src="https://user-images.githubusercontent.com/22763282/163399409-314ab7ec-bfbb-4397-ab9b-6995796f7e5c.png">

** URL **
https://data.lsst.cloud/portal/app/?__action=layout.showDropDown&

**Comment by frossie** [comment]
Thanks for the report, we're looking into it.

**Comment by frossie** [comment]
Good job all around - (1) you have found a bug and (2) we have apparently already fixed it in the codebase. It should get deployed next week, and I'll leave the ticket open till that happens.

**Comment by igorandreoni** [comment]
This is great to hear, thank you Frossie!

**Comment by frossie** [comment]
I can confirm that the upcoming portal release does fix this issue (see screenshot from our integration environment). It's a big release and folks would like more testing time, but I am inclined to take the calculated risk and push it out this Patch Thursday. Will update. 

PS. Thank you for an excellent bug report,  made it very easy to reproduce. 

<img width="682" alt="Screenshot of Safari (2022-04-19, 20-17-06)" src="https://user-images.githubusercontent.com/1933621/164143460-5971b1bb-9c2f-4d26-b8b0-de28b76516b1.png">

**Comment by frossie** [comment]
Sadly we were not able to clear testing in time for this week's Patch Thursday (it's a big update) - so this will be out in production next week.

**Comment by igorandreoni** [comment]
Thanks for the update, Frossie. There is no urgency on my end. Looking forward to the big deployment!

**Comment by frossie** [comment]
I am sorry forgot to update and mention we deployed last week! Try it now :-)

**Comment by igorandreoni** [comment]
It seems to work nicely now. Thanks again!
