### ISSUE TITLE
Portal Aspect of the Rubin Science Platform: no access[BUG] 

### ISSUE THREAD

**Issue by sbonito** [rubin-dp0/Support#27]
After the login in GitHub and entering the https://data.lsst.cloud/ link, if I select Portal I get: 

"504 Gateway Time-out" 

(while the Notebook Aspect works).

This message appears since a couple of days.

Thank you for the support.

**Comment by frossie** [comment]
Sorry about that. Can you try clearing any cookies you have from data.lsst.cloud in your browser and trying again?

**Comment by frossie** [comment]
A fix for the cause for this behaviour was deployed in yesterday's Patch Thursday. The workaround described should no longer be necessary for active users.
