### ISSUE TITLE
Problem trying to acces to the Rubin Science platform API 

### ISSUE THREAD

**Issue by lauramarroo** [rubin-dp0/Support#28]
**Describe the bug**
I'm trying to access to the Rubin science platform using TAP through TOPCAT. 
I use the https://data.lsst.cloud/api/tap as the TAP endpoint.
When TOCPCAT tries to connect to the server, it requires username and password.
According to the https://lsst-lsp-stable.ncsa.illinois.edu/api-aspect the username is  x-oauth-basic and the password is the token.
However, it keeps telling that the authentication failed. I also tried with my username without luck

**To Reproduce**
1. Open TOPCAT
2. Click on Query remote database button
3. Enter the TAP URL: https://data.lsst.cloud/api/tap 
4. Enter username (x-oauth-basic) and password (token)
5. See error: https://data.lsst.cloud/api/tap/tables error: java.io.IOException: Table resource access failure (401 Unauthorized)

**Expected behavior**
Access to the platform

**Screenshots**
![image](https://user-images.githubusercontent.com/107511932/174902262-3ad0c263-28c6-4b06-a43c-0821f97b467d.png)
![image](https://user-images.githubusercontent.com/107511932/174902401-a7c96ed3-8362-4d7f-ae9a-baa3a160d2b2.png)
![image](https://user-images.githubusercontent.com/107511932/174902421-3baf46ce-6b38-46b6-9fb2-25e27e1ffcb6.png)

**URL**

**Desktop (please complete the following information):**
 - Windows 11 Home Single Language, Version 21H2
 - TOPCAT Version 4.8-5, STIL Version 4.1-1
 
**Additional context**
 TOPCAT version
![image](https://user-images.githubusercontent.com/107511932/174902786-be4f6058-1fd9-41b9-9ee8-eacd5f838aa6.png)

**Comment by ktlim** [comment]
If I'm counting the symbols correctly, your token does not look long enough at 22 characters.  That looks like the "public" part of the token without the three character "gt-" prefix nor the "secret" part that comes after a "." character, which is another 22 characters (for a total of 48).

If you did not copy the full token after generating it, you'll have to generate a new one; there's no way for anyone to recover the full token.

**Comment by lauramarroo** [comment]
Yes, i used it also, i copied the token with 48 character and it didn't work

[image: image.png]

[image: image.png]
