### ISSUE TITLE
[BUG] ADQL query box steals Command-` key combination in Mac OS

### ISSUE THREAD

**Issue by wmwv** [rubin-dp0/Support#29]
**Describe the bug**

The ADQL Query box steals my "Alt-`" which I use to switch between windows of an application on Mac OS Monterey.

**To Reproduce**
1. Go to the Portal  
2. Click on 'Select Query Type'->'Edit ADQL (advanced)'
3. Scroll down to 'ADQL Query'
4. Click on the active text box.  Now "Alt-`".  You will get a pair of "``" in the textbox instead of switching to the next window of the application.

**Expected behavior**

I expected to switch to the next window of the application.  If the cursor is not in the text box on that web page the switching works fine, but if the text box is open then you get pairs of "``".

**Screenshots**

<img width="957" alt="Screen Shot 2022-06-28 at 14 28 15 " src="https://user-images.githubusercontent.com/3201257/176256151-53e0d7e1-8db7-4a90-80d7-20e965ad9898.png">

**URL**
If applicable, cut and paste the URL from your browser at which the issue occurred

https://data.lsst.cloud/portal/app/

**Desktop (please complete the following information):**
 - OS: Mac OS 12.4
 - Browser: Safari
 - Version: 15.5

**Comment by gpdf** [comment]
From a macOS perspective, I assume you are talking about "Command-`"?  "Alt" is more commonly mapped to macOS "Option".

I can reproduce this, if so.

**Comment by wmwv** [comment]
Sorry, "Command".  (That's why I get for submitting bug reports while watching a workshop talk...)

**Comment by MelissaGraham** [comment]
@gpdf and @frossie, just checking in, is this a bug that can be fixed, and so the issue should stay open?

**Comment by gpdf** [comment]
We haven't had time to investigate this one yet, to determine whether the colorized-code widget that we are using is configurable to avoid this.  So let's leave this open for a bit.

**Comment by gpdf** [comment]
This behavior is not currently present with Firefox.  Will recheck shortly with the current version of Safari and then decide how to proceed further.

**Comment by frossie** [comment]
Sorry for the delay, this has been identified as a bug in a third party library, we have upstreamed a fix and we're waiting for it to shake down the release chain before we deploy it on data.lsst.cloud.

**Comment by wmwv** [comment]
Great!  Thanks very much.

**Comment by gpdf** [comment]
My apologies for the late update.  This was [fixed](https://github.com/Caltech-IPAC/firefly/pull/1436) in [Firefly-2023.3.0](https://github.com/Caltech-IPAC/firefly/blob/dev/docs/older-release-notes-2023.md) at the end of last year, and the fix was deployed in the last Portal version before the UI changes.  This is also working correctly in the recent new-UI versions of the Portal.
