### ISSUE TITLE
[BUG] Minor text suggestions for 01_Intro notebook

### ISSUE THREAD

**Issue by JoanneBogart** [rubin-dp0/Support#3]
**Describe the bug**
There are several minor typos or places where the text could be clearer. There is one place (eighth bullet below) where the text doesn't seem to go with the output.

**To Reproduce**
Read through the notebook

**Expected behavior**
Here are a list of suggested changes:

* Misspelling in third paragraph:   verticle —> vertical
* Last paragraph in section 1.1: the second “as” in the second sentence should be deleted.
* Typo in text preceding “What version of the LSST Science Pipelines..” code cell.   ot —> of
* First Hazard Warning: grammar mismatch of persons.  Either change “functionality” to “functionalities” or “are” to “is”
* Code cell starting with “import pandas” generates a warning. Text above says “this code produces no output”, which is true but misleading - depends on what you mean by “output”
* Section 2.2, first paragraph, last sentence.  Missing verb in the clause following “and”.   Suggest inserting “can be found” just before “in the DESC’s DC2 paper”
* Section 2.2, fourth paragraph.  For added clarity, suggest changing “remove the #” to “remove all the #” and “Replace the #” with “replace all the #”.
* Still in section 2.2.   “Action: Print all columns names (field names) in the DP0.1 DC2 object catalog” doesn’t seem to be what the results actually are.  They’re not DC2 object catalog fields; they appear to be TAP_SCHEMA fields
* Section 2.3, second paragraph.  In final clause, change “far to many rows” to “far too many rows”
* Before plotting discussion at the end of section 2.4 maybe add heading, e.g. 2.4.2 Make the plot or something like that, parallel to the 2.4.1 heading
* Typo in paragraph just before “Action: Use plt.plot …”.   Change “but briefly the are” to “but briefly they are”
* Section 3.1. Action: Create an instance of the butler…. It says there will be no output but I did get an informational message.  Maybe earlier on define what is meant by “output” in the context of the notebook?
* Delete commented-out line
 # registry = butler.registry

**Screenshots**
N/A

**URL**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Chrome
 - Version: Version 91.0.4472.106

**Smartphone (please complete the following information):**
N/A
 - Version

**Additional context**

**Comment by JoanneBogart** [comment]
Sorry about all the labels.  I didn't consciously add them and spent a while - unsuccessfully -  trying to figure out how to remove most of them.

**Comment by ktlim** [comment]
I believe the labels come from the issue template, which lists all possible labels instead of what is supposed to be an issue type label.

**Comment by frossie** [comment]
Sorry, I have removed the label spam from the issue template. More substantively thank you so much for taking the time to send feedback on our tutorial notebooks, the Community Engagement Team curates them and  will pick up your comments next week.

**Comment by JoanneBogart** [comment]
I have a similar list of typos, etc. for the second notebook.  I'll make another issue.

**Comment by JoanneBogart** [comment]
>  More substantively thank you so much for taking the time to send feedback on our tutorial notebooks
You're welcome!  Happy to do it if it's useful.

**Comment by MelissaGraham** [comment]
All changes have been made (branch tickets/PREOPS-586, https://jira.lsstcorp.org/browse/PREOPS-586).
Changes pushed to main and prod.
All done!
