### ISSUE TITLE
[BUG] The "Logout" button/tab hangs down below header and obscures "xy-tbl" button

### ISSUE THREAD

**Issue by wmwv** [rubin-dp0/Support#31]
**Describe the bug**

In the Portal chart display view, the "Logout" button hangs down below header bar and partially obscures "img-xy" and "xy-tbl" buttons.

**To Reproduce**
1. Go to the Portal and submit a query
2. Get the results back with the table and the plot
3. Try to find the "xy-tbl" button in the upper right.
4. It was hard to find the "xy-tbl" button because it was obscured by the "Logout" button.

**Expected behavior**

I expect that the UI buttons would not overlap each other.

**Screenshots**

<img width="268" alt="Screen Shot 2022-06-28 at 14 56 58 " src="https://user-images.githubusercontent.com/3201257/176261158-eb0ece34-d916-4060-9870-177fdbe5aa00.png">

**URL**
[If applicable, cut and paste the URL from your browser at which the issue occured
](https://data.lsst.cloud/portal/app/?__action=table.search&request=%7B%22startIdx%22%3A0%2C%22pageSize%22%3A100%2C%22serviceUrl%22%3A%22https%3A%2F%2Fdata.lsst.cloud%2Fapi%2Ftap%22%2C%22QUERY%22%3A%22SELECT%20diasrc.ra%2C%20diasrc.decl%2C%20diasrc.diaObjectId%2C%20diasrc.diaSourceId%2C%20diasrc.filterName%2C%20diasrc.midPointTai%2C%20scisql_nanojanskyToAbMag(diasrc.psFlux)%20AS%20psAbMag%2C%20ccdvis.seeing%20FROM%20dp02_dc2_catalogs.DiaSource%20AS%20diasrc%20JOIN%20dp02_dc2_catalogs.CcdVisit%20AS%20ccdvis%20ON%20diasrc.ccdVisitId%20%3D%20ccdvis.ccdVisitId%20WHERE%20diasrc.diaObjectId%20%3D%201252220598734556212%20AND%20diasrc.filterName%20%3D%20%27i%27%22%2C%22MAXREC%22%3A50000%2C%22META_INFO%22%3A%7B%22title%22%3A%22dp02_dc2_catalogs.DiaSource%20-%20data.lsst.cloud%2Fapi%22%2C%22tbl_id%22%3A%22tbl_id-c7f-8%22%7D%2C%22tbl_id%22%3A%22tbl_id-c7f-8%22%2C%22id%22%3A%22AsyncTapQuery%22%2C%22__searchID%22%3A1656442576145%7D&options=%7B%22backgroundable%22%3Atrue%2C%22showFilters%22%3Atrue%2C%22showInfoButton%22%3Atrue%2C%22pageSize%22%3A100%7D)

**Desktop (please complete the following information):**
 - OS: MacOs 12.4
 - Browser: Safari
 - Version: 15.5

**Additional context**

**Comment by wmwv** [comment]
Perhaps moving the "tri-view" "img-tbl" "img-xy" and "xy-tbl" buttons to the upper-left would be an easy solution and make those buttons easier to fine in any case.

**Comment by ktlim** [comment]
This also appears elsewhere in the Portal where toolbar buttons may be obscured.  I think "Logout" is in the wrong place for some reason.

**Comment by gpdf** [comment]
This was a known problem before the snapshot release for the start of DP0.2 was taken; fixed in the upstream.

https://github.com/Caltech-IPAC/firefly/pull/1231

**Comment by gpdf** [comment]
Fixed by the deployment of a Portal build based on [Firefly 2022.2](https://github.com/Caltech-IPAC/firefly/releases/tag/release-2022.2.1) on July 28th.

**Comment by wmwv** [comment]
I confirm that things look good now.  Thanks.
