### ISSUE TITLE
DP0.2 Tutorial 02. Explore a SN1a Lightcurve

### ISSUE THREAD

**Issue by kcdage** [rubin-dp0/Support#33]
Hello! I just worked through the second tutorial about SN1a lightcurves (https://dp0-2.lsst.io/tutorials-examples/portal-intermediate.html), and noticed that while this is supposed to be plotting the i band lightcurve, the suggested y label in section 3. says it is the "apparent magnitude (r)".  

Also, I know that a previous section went over what the psABMag is, but in the section 2 query, it might be helpful to reiterate that. 

thank you!!

**Comment by MelissaGraham** [comment]
Thank you @kcdage, the Community Engagement Team will address this issue and report back when it is done.

For Rubin staff: https://jira.lsstcorp.org/browse/PREOPS-1297

**Comment by Madejski** [comment]
Sharp eyes, Kristen! - thanks for noting it.  We fixed it, and merged the updated version into main.  Please feel free to let us know if you see anything else that needs fixing!  --Greg

**Comment by Madejski** [comment]
I think this is now fixed and can be closed.  --Greg
