### ISSUE TITLE
Portal temporal constraints won't take MJD

### ISSUE THREAD

**Issue by MelissaGraham** [rubin-dp0/Support#36]
**Describe the bug**
The Portal's temporal query option will not let me enter an MJD, but it will take ISO and properly convert to MJD.

**To Reproduce**
1. Go to data.lsst.cloud, enter Portal Aspect.
2. Choose the visit table.
3. Enter spatial constraints "62, -37", Cone, 5 degrees.
4. Click box for Temporal constraints. For Temporal Column enter "expMidptMJD".
5. Click "MJD" (instead of default "ISO"). Enter 60500 into box for start time. Notice error.

**Expected behavior**
Expected to be able to enter a valid MJD.

**Screenshots**
<img width="581" alt="Screen Shot 2022-10-18 at 3 34 23 PM" src="https://user-images.githubusercontent.com/13826801/196558054-c2f82dec-0e49-4a6d-b03b-a942537dd4a3.png">

**URL**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.6
 - Browser: Chrome
 - Version: 106.0.5249.91 (Official Build) (x86_64)

**Additional context**
If I instead enter a date in ISO format then click MJD to convert to MJD it's happy with that.

**Comment by gpdf** [comment]
Confirmed and investigating.

**Comment by gpdf** [comment]
This is now fixed.

**Comment by gpdf** [comment]
Closing as completed
