### ISSUE TITLE
[BUG] JupyterLab fails to save changes to notebooks, text files

### ISSUE THREAD

**Issue by duncanwood** [rubin-dp0/Support#38]
**Describe the bug**
Files fail to save while editing. Both notebooks and text (.py) files, apparently at the same time. Persists until refreshing page, which loses any changes since last successful save. 

**To Reproduce**
???

**Expected behavior**
Expected files to either autosave or successfully manually save.

**Screenshots**
![Screen Shot 2022-11-07 at 12 44 15](https://user-images.githubusercontent.com/7288228/200412229-32f2769a-4292-475a-a072-7ed0f0fe2593.png)

**URL**
If applicable, cut and paste the URL from your browser at which the issue occurred

**Desktop (please complete the following information):**
 - OS: macOS 12.6.1 
 - Browser: Chrome Version 107.0.5304.87 (Official Build) (arm64)

**Additional context**
Has happened at least a couple times, first time lost 4 hours of changes.

**Comment by duncanwood** [comment]
Hi Melissa.

Here are two URLs that failed to save:
https://usdf-rsp.slac.stanford.edu/nb/user/duncanw/lab/tree/notebooks/bias-shifts/shifts_2022_11_01-multiprocessing.ipynb
https://usdf-rsp.slac.stanford.edu/nb/user/duncanw/lab/tree/repos/lsstcam-bias-shifts/bias_shifts.py
The failure to save is intermittent, and relatively infrequent, so I don't think it's related to the above permission error. I'm confused why it would present as a permission error.

In my encounters with the bug, I am able to make edits and save the files immediately after refreshing the page.

I'm not sure about the previous episodes, but the bug happened today, just before posting this report, on a session that I opened this morning. That is assuming "session" means launching the portal with a browser - I haven't spawned a new server in probably a couple weeks. If I should be shutting down the server when I'm done working for the day, for example, then that could be a red flag here.

**Comment by frossie** [comment]
Hello I notice that you are asking a question about the RSP deployed at the USDF. As a project user you have access to support for that deployment on the #ops-usdf slack channel and the project JIRA system - these Github issues are primarily for users of the science RSP at data.lsst.cloud.

**Comment by frossie** [comment]
See https://lsstc.slack.com/archives/C027902HL8H/p1667861271885699 on the project slack for a discussion of your issue and any followup
