### ISSUE TITLE
Kernel died on Jupyter notebooks tutorials

### ISSUE THREAD

**Issue by silviapietroni** [rubin-dp0/Support#43]
Hello, I have some troubles with Jupyter notebooks tutorial 3b and 3c, at some point I get this error (please see pic).
 I restarted the kernel, logged out and logged in again, but it does not work.
Tutorials n. 1, 2 and 3a are ok. Still have to try the others.
Thanks
![Kernel died](https://user-images.githubusercontent.com/124257478/222170804-600708e8-0603-48bb-87bc-dacd6cb4119e.png)
(url)

**Comment by timj** [comment]
Are you using a large node for this work?

**Comment by MelissaGraham** [comment]
NB 03b needs a medium container, and NB 03c needs a large container. That is probably the cause of the kernel issue. @silviapietroni  let us know if using a large kernel works for you?

As a side note, I can see that in the Firefly tab, the "RSP TAP Search" has been clicked, the view navigated away from the image display, and is now on the Portal query interface. It's not wrong but NB 03b does not instruct users to do this so, just in case this is useful: click "Add Chart" and then "OK" in the pop up to resume interactions with the Firefly display.

**Comment by gpdf** [comment]
Also just the "Cancel" near the bottom center should return the user to the original image display.

**Comment by silviapietroni** [comment]
Dear Melissa and dear all, I've tried to click "Add Chart" and then "OK" in the pop up ma it does not work anyway (I receive the message in the picture, so no possibility to click on "cancel").
About the kernel: I'm running the notebooks on the portal and not on my laptop, don't know if this could answer to your question. So I do not know the dimension of the kernel, is there a way to verify that?
Best
![image](https://user-images.githubusercontent.com/124257478/222406387-65ed4bcf-4b73-4e60-8392-3beb8ff82198.png)

**Comment by silviapietroni** [comment]
Thank you very much, it works now! (both).
Just to be sure: this is the image I get from the NB 03b, in a new tab
![image](https://user-images.githubusercontent.com/124257478/222515063-1154861c-b3cb-4598-a129-c50684e83e00.png)
Then do I have to close the issue?
