### ISSUE TITLE
[BUG] Link to troubleshooting tips is broken

### ISSUE THREAD

**Issue by igorandreoni** [rubin-dp0/Support#45]
**Describe the bug**
In the README.md file, the link to the troubleshooting tips leads to a 404 error page.

**To Reproduce**
1. in the repo main page, click on https://dp0-1.lsst.io/data-access-analysis-tools/index-nb-intro.html#troubleshooting-tips

**URL**
[If applicable, cut and paste the URL from your browser at which the issue occurred](https://dp0-1.lsst.io/data-access-analysis-tools/index-nb-intro.html#troubleshooting-tips)

**Comment by ktlim** [comment]
Looks like the URL should be https://dp0-2.lsst.io/data-access-analysis-tools/nb-intro.html#troubleshooting-tips (and have the text refer to DP0.2).

**Comment by MelissaGraham** [comment]
Thank you Igor! I have fixed the README file, and am closing this issue.
