### ISSUE TITLE
Configure RSP Notebook aspect to not show "Would you like to receive official Jupyter news" box doesn't appear

### ISSUE THREAD

**Issue by wmwv** [rubin-dp0/Support#48]
**Is your feature request related to a problem? Please describe.**

It's annoying when the "Would you like to receive official Jupyter news" box appears when starting up JupyterHub.  It seems inappropriate for a service with lots of users.

**Describe the solution you'd like**

I'd like to not see this box.  I'd like others to not see the box.

**Describe alternatives you've considered**

One can click the X and close the box.  But then it appears again the next time.

**Additional context**

<img width="428" alt="Screen Shot 2023-06-01 at 19 26 23 " src="https://github.com/rubin-dp0/Support/assets/3201257/ad4f3f27-6e0c-41a5-ab5d-ec0d5b36ddc3">

**URL**
https://data.lsst.cloud/nb/user/wmwv/

**Comment by frossie** [comment]
Yeah that's new and annoying and on the list to see whether we can stop it

**Comment by athornton** [comment]
Addressing in https://jira.lsstcorp.org/browse/DM-39612

Note that any fix will only apply to images built after that date.  So it's gonna be in "recommended" as long as "recommended" is w_21.

**Comment by MelissaGraham** [comment]
Since a fix has been identified and implemented, and will be available when we next bump the recommended image at the RSP, I'm closing this ticket, thanks all.

**Comment by wmwv** [comment]
I still see the "Would you like ..." message in Weekly 2023_21, Weekly 2023_29, and Daily 2023_07_23

<img width="755" alt="Screenshot 2023-07-25 at 16 47 45" src="https://github.com/rubin-dp0/Support/assets/3201257/a4d4f05b-b8ef-45be-a0e0-ff3cd263a0fe">
<img width="602" alt="Screenshot 2023-07-25 at 16 25 34" src="https://github.com/rubin-dp0/Support/assets/3201257/79442ad5-a4e8-4d9e-a549-02c65c225f54">
<img width="614" alt="Screenshot 2023-07-25 at 16 41 06" src="https://github.com/rubin-dp0/Support/assets/3201257/87ffd171-b259-46c1-90a2-87d281980741">
