### ISSUE TITLE
[BUG] Minor text suggestions for 02_Intermediate_TAP_Query notebook

### ISSUE THREAD

**Issue by JoanneBogart** [rubin-dp0/Support#5]
**Describe the bug**
There are some typos and a couple instances of unused code.

**To Reproduce**
Read through the notebook

**Expected behavior**
Here are a list of suggested changes:
* First Hazard Warning: same mismatch of grammatical person as for 01 notebook
* In code cell following that warning, missing word “of” in second comment line:  # Get an instance [of] the TAP service
* As in 01_Intro, change  
"The object catalog is described in the DESC's DC2 data release note, and more information about the simulated data in the DESC's DC2 paper."     to 
"The object catalog is described in the DESC's DC2 data release note, and more information about the simulated data may be found in the DESC's DC2 paper."
* First paragraph in section 2.2:  “The following” would seem to refer to the remainder of section 2.2.  Rather than the phrase “and join the object table with the truth table”, I suggest  ending the sentence after “degrees” and adding a separate sentence about the join, e.g. “In the next section additional constraints are imposed on the selection by joining with the truth table.”
* 2.3 second sentence:  “aslo” —> “also”
* 3.1 third sentence:  “ot” —> “or”
* 3.2 first code cell: variable “hover_tool” isn’t used
* 3.3 first sentence missing word:   “..and make use [of] the advanced..”
* 3.3 second sentence : “crowed” —> “crowded”
* 3.3 first paragraph, last sentence : “ony” —> “only”
* 3.3 Third code cell.   This doesn’t appear to be used for anything
* 3.4 Comment in first code cell: delete “to add” so it reads 
            “# Another way data can be added to the CDS”
* 3.4 Second code cell: variable “hover_tool” isn’t used
**Screenshots**
N/A

**URL**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Chrome
 - Version: 91.0.4472.106

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by JoanneBogart** [comment]
I would add the "Documentation" label but I don't see a way to do it.

**Comment by gpdf** [comment]
Thank you very much for your careful copyediting, @JoanneBogart .

**Comment by MelissaGraham** [comment]
All changes except the following have been made (branch tickets/PREOPS-586, https://jira.lsstcorp.org/browse/PREOPS-586).

3.2 first code cell: variable “hover_tool” isn’t used
 --> MLG this is necessary to define, did not delete

3.3 Third code cell. This doesn’t appear to be used for anything
 --> MLG this is adding the hover tool and defining other tools, as noted in the comments

3.4 Second code cell: variable “hover_tool” isn’t used
 --> MLG this is necessary to define, did not delete

Changes pushed to main and prod.
All done!

**Comment by JoanneBogart** [comment]
I still don't see that those particular hover tools I mentioned are needed.  For the first item I mentioned, I commented out the line defining hover_tool and everything worked just fine.   That variable is not used below.  Instead, in the next cell there is 
```p.add_tools(HoverTool(tooltips=tooltips))```
That's the code that defines and adds the hover tool.

The code under 3.4 is similar: The variable `hover_tool` is defined but not actually used. 

For 3.3, if I leave the code as is.  the information displayed when hovering comes from
```
hover = HoverTool(tooltips=[("(RA,DEC)", "(@ra, @dec)"),
                            ("(g-r,g)", "(@gmr, @gmag)"),
                            ("objectId", "@objectId"),
                            ("type", "@truth_type")])
```
only.  The code defining `hover_tool` in the cell above has no effect that I can see.

**Comment by MelissaGraham** [comment]
See also: https://github.com/rubin-dp0/tutorial-notebooks/issues/23
