### ISSUE TITLE
[BUG] error when trying to login in Notebook 

### ISSUE THREAD

**Issue by marcelolucas11** [rubin-dp0/Support#50]
**Describe the bug**
error when trying to login in Notebook with credential UFRGS (Federal Universiy of Rio Grande do Sul).

**To Reproduce**
1. Go to 'https://data.lsst.cloud'
2. Click on 'Notebooks'
3. Select an Identity Provider 'UFRGS.'
4. Click on 'Log On'
5. See error

**Screenshots**
![image](https://github.com/rubin-dp0/Support/assets/57026830/1b290508-2510-40a4-aa76-b6b2a1606767)

**Desktop (please complete the following information):**
 - Windows
 - Browser [Opera]

**Comment by frossie** [comment]
Hi could you please go to https://cilogon.org and see if you can sucessfuly connect with UFRGS and let us know the result. 

If that works, it is an RSP issue and we can investigate it. If it does not, I can help you report the issue to your provider .

**Comment by marcelolucas11** [comment]
> Hi could you please go to https://cilogon.org and see if you can sucessfuly connect with UFRGS and let us know the result.
> 
> If that works, it is an RSP issue and we can investigate it. If it does not, I can help you report the issue to your provider .

HI, same error.

**Comment by marcelolucas11** [comment]
HI, same error.

**Comment by frossie** [comment]
Okay so let me explain what is happening and what you can do about it. 

The RSP at data.lsst.cloud uses InCommon authentication through CILogon, a service provided by NCSA. Participating institutions provide servers that can authenticate their users according to a common standard. 

If your institution is not working the most probable reasons are:
1. Your institution's InCommon server is misconfigured
2. The CILogon's service entry about your institution's server is incorrect or out of date. 

I suggest that you forward a link to this issue to your institution's IT and ask them to follow up on this. Meanwhile, if you are a participant to the LSST Data Preview program, you can sign up to the RSP with one of the more general methods (Github, ORCID, Google, etc).
