### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by marcelolucas11** [rubin-dp0/Support#51]
**Describe the bug**
Hi, I had the error of not being able to enter the notebooks with my college login, so I had the idea of redoing the login, but with github, now the error is another one. How do I leave only login by github ?

![image](https://github.com/rubin-dp0/Support/assets/57026830/76609c41-efa3-4482-be87-1af8c02f39c3)

**Comment by frossie** [comment]
Hi you seem to have tried this twice (or something like that) and the system is confused - it is showing marcelolucas and 'marceloclucas. I will delete both so you can start again.

**Comment by marcelolucas11** [comment]
> Hi you seem to have tried this twice (or something like that) and the system is confused - it is showing marcelolucas and 'marceloclucas. I will delete both so you can start again.

But what about my saved stuff?

**Comment by frossie** [comment]
Alright try again now, following the instructions. It can be a bit confusing so I recommend you follow along with the video at https://rsp.lsst.io/guides/getting-started/get-an-account.html

Let me know what happens.

**Comment by frossie** [comment]
> > Hi you seem to have tried this twice (or something like that) and the system is confused - it is showing marcelolucas and 'marceloclucas. I will delete both so you can start again.
> 
> But what about my saved stuff?

It will be there under whichever of the two usernames you used to generate it so when you sign up again use that one

**Comment by frossie** [comment]
By the way if you can remember when/how you ended up with two different accounts that would be helpful. We think there is a CIlogon fix to the reason this can sometimes happen, but it would be good to make sure this isn't something else.

**Comment by marcelolucas11** [comment]
I was unable to access my account through my college login, so I did the new account step by step with the GitHub login, thus ending up with two accounts. I didn't think they would have conflicts.

**Comment by frossie** [comment]
i see you closed the ticket - all good now?

**Comment by marcelolucas11** [comment]
Yes, thanks for helping me.
