### ISSUE TITLE
[BUG] Unable to Login

### ISSUE THREAD

**Issue by MrNasaMan** [rubin-dp0/Support#52]
**The bug**
I am unable to login into the portal located at https://data.lsst.cloud/ . Every time I try to log in with my identity provider, which is GitHub in my case, it cannot find my account. It keeps redirecting to a self signup page. When I tried to click it , I get an error. The thing is that in the notifications it says that I got approved but when I tried to click on it I get another error.  I used GitHub to sign up for my account. Not too sure what the issue is right now. I have added some screenshots and video demonstration below.

**Screenshots**
[issue p1](https://github.com/rubin-dp0/Support/assets/109177113/2bd303bf-7e34-4724-b843-67b4333f6254)

**Video Demonstration**

https://github.com/rubin-dp0/Support/assets/109177113/7c382a26-aa03-4b39-bd76-7797123b4529

**Desktop**
 - OS: Windows
 - Browser: chrome, 

User Info:
Username: Jermuk
Name: Davit K.
DP0

.

**Comment by frossie** [comment]
Love the video demonstration, super helpful. Could you try from a private browser window if you have not done that already and see if anything is different?

**Comment by frossie** [comment]
Also, have you ever successfully logged on or is this your first time

**Comment by MrNasaMan** [comment]
The only time I have logged in was to self signup. After my petition was approved I was not able to log back in. I have tried use incognito mode but it has made no difference so far. 

Thanks

**Comment by frossie** [comment]
Okay are you at the Rubin PCW meeting this week by any chance?

**Comment by MrNasaMan** [comment]
Uhh, I am very new to all of this so I dont know what the Rubin PCW meeting is.

**Comment by frossie** [comment]
Oh I am sorry the Rubin Project Community Workshop which is currently ongoing.  It's all good, we'll figure it out once the conference wifi decides to behave :-)

**Comment by frossie** [comment]
Okay this is quite fascinating. Your record indicates the enrollment flow was never completed:

<img width="260" alt="Screenshot of Safari (2023-08-10, 22-50-14)" src="https://github.com/rubin-dp0/Support/assets/1933621/24391d41-84df-40bc-8d58-932788605d37">

It would be interestint to know if this is true or in error, but asking you to remember what you were doing on June 6th was a bit of a stretch. I am going to expunge your record and would you please just go through sign-up again? And make sure you reach the stage where the system tells you it has sent you the confirmation email, and then clicking on that email. 

Sorry for the trouble.

**Comment by frossie** [comment]
Okay so you seem to have an incomplete sign-up due to the system having been unable to successfully send email to your gmail account. Which is something we have not seen before. In any case I have expunged your record - if you would just sign up again let's see what happens. 

And apologies for the trouble.

**Comment by MrNasaMan** [comment]
okay thank you

**Comment by MelissaGraham** [comment]
@MrNasaMan  let us know when you've successfully signed in by leaving a comment and closing this ticket?

**Comment by frossie** [comment]
This has been quiet, I am going to close this but feel free to re-open if you're still having difficulties
