### ISSUE TITLE
[BUG] Websocket connection failed in JupyterLab with Chrome

### ISSUE THREAD

**Issue by mkelley** [rubin-dp0/Support#53]
**Describe the bug**
Using Chrome on Ubuntu Linux I can open the JupyterLab portal, but cannot connect to any kernels.  This has been a persistent issue for me over the past year or more.  My workaround is to use Firefox on the same computer, but I prefer to use Chrome.

On the Javascript console, I find the following repeated errors:

```
index.js:114 WebSocket connection to 'wss://data.lsst.cloud/nb/user/msk/api/events/subscribe?token=...' failed: 
(anonymous)	@	index.js:114
_subscribe	@	index.js:107
factory	@	index.js:42
Poll._execute	@	index.es6.js:374
execute	@	index.es6.js:313
```

```
WebSocket connection to 'wss://data.lsst.cloud/nb/user/msk/api/kernels/9f38e77e-e981-4f8e-9c00-421c675f3951/channels?session_id=...' failed: 
KernelConnection._createSocket	@	default.js:73
```

```
WebSocket connection to 'wss://data.lsst.cloud/portal/app/sticky/firefly/events?channelID=ffChan-msk-nb-1692364030-53' failed: 
NPe	@	firefly-c4dab20….js:2
(anonymous)	@	firefly-c4dab20….js:2
kPe	@	firefly-c4dab20….js:2
t	@	firefly-c4dab20….js:2
```

**To Reproduce**
1. Log on to RSP with Chrome
2. Open Notebooks
3. Start a server (e.g., small).  This seems to work fine.
4. Wait for the JupyterLab landing page to open.
5. Open the Javascript console and see websocket connection failed messages.
6. Open a Notebook: see more websocket connection failed messages.  The browser never connects to the kernel.
7. Open a Console: the console tab opens.  Try any command and nothing happens.
8. Open a Terminal: the terminal tab opens and a cursor appears.  I cannot type anything.

Editing files (e.g., text or python files) and browsing directories works fine.

**Expected behavior**
That I could do anything with a python kernel.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04.3 LTS (and up to date)
 - Browser: Chrome 116.0.5845.96 (Official Build) (64-bit) 

**Additional context**

This jypterlab issue might be relevant, although that report is not using wss: https://github.com/jupyterlab/jupyterlab/issues/12222

When I use Firefox on the same system, everything appears to work.  There are no websocket failures on the console.

**Comment by frossie** [comment]
Thanks for the report. Using Chrome under Linux is something that should certainly work, a couple of our engineers use that themselves. 

We're looking it it, meanwhile:

1. Can I get you to paste the status bar of your Jupyterlab window, the one that looks like this:

<img width="557" alt="Screenshot of Safari (2023-08-18, 13-47-07)" src="https://github.com/rubin-dp0/Support/assets/1933621/ae4ec157-f2f5-4230-a158-db65b527881d">

2. Can you try disabling your Chrome extensions (temporarily) and trying from a private browser window?

**Comment by frossie** [comment]
One more thing - can you go to this 3rd party website https://www.piesocket.com/websocket-tester 
from:
1) Your Firefox which works
2) Your Chrome which does not work

click Send (their default settings are fine) and report whether you get the same behavior on both browsers, and include a screenshot of your output. This is what I would expect:

<img width="1035" alt="Screenshot of Safari (2023-08-18, 14-18-49)" src="https://github.com/rubin-dp0/Support/assets/1933621/a8d081f0-bdea-4a6a-b488-2f7ccc8373cb">

**Comment by mkelley** [comment]
I have identical results in Chrome and Firefox with the piesocket tool:
![image](https://github.com/rubin-dp0/Support/assets/1138643/460f210b-76a6-4987-8bc6-e2f02990f947)

The status bar with Chrome is:
![image](https://github.com/rubin-dp0/Support/assets/1138643/009614ac-31a8-429a-ada3-7fd8d90ce03d)

**Comment by mkelley** [comment]
Also, neither disabling extensions nor private browsing mode was successful.

**Comment by mkelley** [comment]
The errors are different today.  Now I am seeing 302 errors, e.g.,:

```
WebSocket connection to 'wss://data.lsst.cloud/nb/user/msk/api/events/subscribe?token=...' failed: Error during WebSocket handshake: Unexpected response code: 302
(anonymous) @ index.js:114
```

**Comment by frossie** [comment]
So we have been unable to reproduce this and the most likely (though not certain) explanation is that there is something in your configuration that is disabling websocket connections. Is there any way you could try from a different device and/or network?

**Comment by mkelley** [comment]
I've tried this on three different computers on three different networks,
including just now from a hotel.  All three computers have ubuntu, although
different installations.  All three use the latest google-chrome-stable
from http://dl.google.com/linux/chrome/deb .  My only option left for
testing is to try it on an EC2 instance or something similar, unless you've
already done that.

**Comment by frossie** [comment]
Hi I am sorry we're kinda out of ideas since we can't reproduce it any way we try. If your timezone permits can you sign up for our zoom office hour and we can try and watch what's happening? You can sign up here: https://fantastical.app/frossie/ask-square

**Comment by frossie** [comment]
(by the way if you're always logging onto your Chrome wit the same google account, the different computers aren't really testing anything different if you have a Chrome setting disabling websockets, but if you drop in for office hours we can check for that)

**Comment by mkelley** [comment]
I have been able to run a notebook from an identical version of Chrome installed on a different linux distribution, so I can now rule out Chrome version and logging into my browser as the cause.  I have also successfully run notebooks with Chrome on my same computer, just using a different (fresh) user account.  It clearly seems to be a problem hyper local to myself.  I'll close the issue.  Thanks for the help!

**Comment by frossie** [comment]
Ah. If you ever figure out why your (older) user account had an issue, do let us know, but glad you're up and running!
