### ISSUE TITLE
[BUG] Can't login Rubin Science Platform

### ISSUE THREAD

**Issue by hbgon** [rubin-dp0/Support#54]
**Describe the bug**
I try to login on data.lsst.cloud with my institutional account (@ufrgs.br) but keep getting the same error as showed below 

**Screenshots**
![ss2](https://github.com/rubin-dp0/Support/assets/126601575/2e58b553-ac11-4a77-bded-83f3a997ac78)
![ss1](https://github.com/rubin-dp0/Support/assets/126601575/449d1df1-7fe2-40ae-b988-e0ecf7461f55)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [116.0.5845.96  64 bits]

**Additional context**
Months ago I submitted a petition to hold a Rubin Science Platform (RSP) account using my "@[gmail.com]" email account because I didn't have my @ufrgs.br yet. But now I do and wasn't able to apply again.

What should I do?

**Comment by jeffcarlin** [comment]
You should have received an email from Melissa Graham on April 6 asking to confirm your data rights. Because it was never confirmed that you are a data rights holder, your petition for an account was denied.

I will reach out to you at your gmail address with more details.

**Comment by jeffcarlin** [comment]
Resolved the issue over email with the user.
