### ISSUE TITLE
[BUG] Missing comma

### ISSUE THREAD

**Issue by gschwend** [rubin-dp0/Support#56]
**Describe the bug**
    A very simple bug fix: the two queries in section 3.2.1 and 3.2.2 of notebook `DP02_02_Catalog_Queries_with_TAP.ipynb` miss a comma between the column names `detect_isPrimary` and `g_cModelFlux`.  

**To Reproduce**
1. Go to notebook `DP02_02_Catalog_Queries_with_TAP.ipynb`
2. Run all the cells up to section 3.2.3
3. See the error in the display of the dataframes attributed to the variables `results_table` and `results1_table`. The column `detect_isPrimary` is missing and the column `g_cModelFlux` appears as a boolean data in the resulting dataframes. 

**Expected behavior**
`detect_isPrimary` should show boolean data and `g_cModelFlux` floats.  

**Screenshots**
![image](https://github.com/rubin-dp0/Support/assets/9534570/f2f88aa0-d71d-4719-a162-cd268f00c426)

![image](https://github.com/rubin-dp0/Support/assets/9534570/7b63f7d0-280f-4078-ad23-bbac46f105f3)

**Comment by jeffcarlin** [comment]
Thanks for catching this, Julia! I have fixed the error in the notebook, and merged it to the `main` and `prod` branches, so you should see a "repaired" version of the notebook the next time you log in.

**Comment by gschwend** [comment]
You're welcome! I tried to fix it myself in a separate branch with the intention of opening a pull request, but I encoutered a permission barrier (which makes sense!). Thanks for the quick response :)
