### ISSUE TITLE
[BUG] Identifier (SORID) variable "OIDC_CLAIM_sub" not set"

### ISSUE THREAD

**Issue by broukema** [rubin-dp0/Support#58]
**Describe the bug**

My attempts to create a login at https://data.lsst.cloud failed
at the self-signup stage from two different identity providers.

**To Reproduce**

* 1.1 https://data.lsst.cloud/  
* 1.2 click on "Log in" 
* 1.3 allow access by:
   * script: code.jquery.com
   * script: cdns.jdelivr.net
   * script: HHHHHHHHHHHH.statuspage.io  (where HHHHHHHHHHHH is a 12-character alphanumeric string)
   * frame:  HHHHHHHHHHHH.statuspage.io (same string)
* <nowiki>2.+3.</nowiki> and three select Nicolaus Copernicus University (NCU) and login using our centralised login server
   * the first time I did this, earlier today, I agreed to send the listed pieces of info to CILogon. On repeating the step now, I have not been asked about whether I agree to send the info (since the NCU server login.umk.pl presumably has stored my earlier agreement - the first time around, I clicked a box saying that I don't need to confirm every time).
* <nowiki>4.</nowiki> Onboarding flow: Identity provider selection
   * This is still set at Nicolaus Copernicus University, so I left it unchanged.
* <nowiki>5.</nowiki> Self Signup With Approval
   * Click on "BEGIN ->"
   * 5.1 two info boxes flash up briefly about some things being done
   * 5.2 There's
      * a warning popup box `Identifier (SORID) variable "OIDC_CLAIM_sub" not set` (white text, red background); and
      * [icon 'i'] `The identifier "http://cilogon.org/serverE/users/XXXXXX" is not registered. If your request for enrollment is still being processed,you will not be able to login until it is approved. Please contact an administrator for assistance.` (black text, yellow background; XXXXXX is a 6-digit number)

This sequence of steps is reproducible, except that I clicked the X to remove the `Identifier ...` box, and it no longer appears on repeats.

The value XXXXXX is identical each time.

* Repeat 2-5 with ORCID, gets to
   * 5.2   `The identifier "http://cilogon.org/serverE/users/YYYYYY" is not registered. If your request for enrollment is still being processed, you will not be able to login until it is approved. Please contact an administrator for assistance.` where YYYYYY is a different number, about 300 greater than XXXXXX, done something like 10 hours later than when I first tried to register.

**Expected behaviour**

I expected to be requested to give my given+family name and an email address, as in step 5 of https://rsp.lsst.io/guides/getting-started/get-an-account.html

**URL**

The final URL, at step 5.2, is https://id.lsst.cloud/registry/

**Desktop (please complete the following information):**
 - Device: desktop computer (two different ones)
 - OS: Debian GNU/Linux Bookworm 12.2
 - Browser: firefox-esr
 - Version: 115.3.0esr-1~deb12u1
 - Plugins for privacy: 
    -  uMatrix (see 1.3 above for third-party scripts and a frame that I allowed); 
    - Privacy Badger (doesn't seem to have blocked anything); 
    - uBlock Origin (doesn't seem to have blocked anything)

**Additional context**

The variable OIDC_CLAIM_sub is described at  https://www.cilogon.org/oidc .

**Comment by drjenncash** [comment]
Just adding that my student and I have both encountered the same error in the last two days. (Using GitHub as the authenticator since we are at a small school). 

Please keep us up to date on a fix if it becomes available. 

Jennifer Cash
Deidre Gilliard

**Comment by frossie** [comment]
Hi sorry about this - our authentication provider has now fixed this - please try again and let us know.

**Comment by broukema** [comment]
I got through several further steps this time, through to `We are reviewing your application. You’ll receive an email as soon as your account is approved.` So the bugs looks solved to me.

@drjenncash Could you please confirm that the bug is solved for you and your student too? Then I'll close it.

**Comment by drjenncash** [comment]
That bug has been fixed for my student and I.

**Comment by MelissaGraham** [comment]
The issue was resolved so I'm closing this ticket.
