### ISSUE TITLE
[BUG] Lost Access to RSP after Loosing Student Account

### ISSUE THREAD

**Issue by bazkiaei** [rubin-dp0/Support#61]
**Describe the bug**
I'm currently facing an access issue with LSST RSP and could use your assistance.
Previously, I utilized my student account credentials to log in to Macquarie University Single Sign On for accessing LSST RSP. However, as I am no longer a student, this method is no longer viable.
I now have a Macquarie University staff account, which I use to log in to Macquarie University Single Sign On. However, attempting to access the RSP redirects me to a page that states "Self Signup With Approval."
Upon trying to sign up on that page, I find myself redirected to a different page, a screenshot of which I have attached to this message.

**Screenshots**

![Screen Shot 2023-11-25 at 2 07 47 pm](https://github.com/rubin-dp0/Support/assets/40375207/eef1383a-8f24-40d0-bb8d-a37fb1e7c321)

**Comment by frossie** [comment]
Do you need files you used with your previous account or just a new account? What username did you have with your student account?

**Comment by bazkiaei** [comment]
Yep, that will be great if I can keep my files from the previous account.

**Comment by MelissaGraham** [comment]
@bazkiaei I think Frossie's going to need to know what username did you have with your student account in order to help here. Do you remember it?

**Comment by bazkiaei** [comment]
Yes @MelissaGraham , I have shared that with her on Slack. Thank you for following up.

**Comment by frossie** [comment]
Issue has been resolved w/ the user. 

Our advice is to link a second identity that you control (eg Github, ORCID) after you sign up with your institutional account to provide a self-serve "escape route" for institutional moves. Here are the instructions: https://rsp.lsst.io/guides/getting-started/linking-more-ids.html
