### ISSUE TITLE
[BUG] Authentication error during account creation

### ISSUE THREAD

**Issue by djbrout** [rubin-dp0/Support#64]
New delegate RSP authentication error. I'm attempting to create an account following the video on the new delegate checklist. No matter how I login (orcid, github, my institution) I'm getting the following error. 

![image](https://github.com/rubin-dp0/Support/assets/5403753/c66bba0a-035f-4f47-a955-ca8d9b21d8b9)

**Comment by sarahdraves** [comment]
Hi! I just encountered the same issue. Using the link provided by @rra got around the problem.

**Comment by MelissaGraham** [comment]
Thanks for reporting @sarahdraves that's very helpful to know.

**Comment by rra** [comment]
We deployed a new version of our authentication software during the patch window today and this problem should hopefully now be properly fixed. Thank you for the report!
