### ISSUE TITLE
[BUG] Onboarding and Login

### ISSUE THREAD

**Issue by mochaait** [rubin-dp0/Support#65]
Hello, I'm not sure if this is a bug necessarily or just my impatience. I attempted to create an account for the platform, wherein I logged in and did the usual steps for the first part. Due to some personal issues, I was unable to verify my email for a few days. I returned to it today to finish the process, logged in, and saw this:

<img width="1512" alt="Screenshot 2024-05-28 at 12 14 19 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/6b997a44-4e0e-4fc5-9ab8-ad8b92714056">

I am unaware if the verification process was terminated or the like, but this was my best thought to reach out. Please let me know if I have erred or are in any other way able to rectify the issue.

**Comment by mochaait** [comment]
Tried logging in once again through CILogon on the Cloud Server. Came up with this error.
<img width="677" alt="Screenshot 2024-05-28 at 12 52 59 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/754ca8e5-952a-4eb7-8509-72898a6feef5">

**Comment by MelissaGraham** [comment]
Hi @mochaait, thanks for reporting this.

Let's first see if the same solution as in this issue (https://github.com/rubin-dp0/Support/issues/64) works for you.

Please go directly to: https://id.lsst.cloud/registry/co_petitions/start/coef:6
You should be able to start the enrollment process from there.

**Comment by MelissaGraham** [comment]
Or just try again, it sounds like the bug was fixed yesterday: https://github.com/rubin-dp0/Support/issues/64#issuecomment-2141087252

**Comment by mochaait** [comment]
Seems like I'm stuck on a white screen now, sadly. 

<img width="1512" alt="Screenshot 2024-05-31 at 10 52 33 AM" src="https://github.com/rubin-dp0/Support/assets/157167291/d671c375-8aff-46d2-acf7-cd8bd0448ad8">

**Comment by MelissaGraham** [comment]
Hi @mochaait , a bit more information would be helpful here. How did you start the process this time, and at what stage of the process does the white screen occur? Did you already try clearing your cache and using a different browser?

**Comment by mochaait** [comment]
I clicked the link, clicked begin in the "Self-Signup With Approval" page, and am left with the blank page. I did try clearing my cache and deleting all of my other tabs just in case, but it seems to remain blank.

**Comment by mochaait** [comment]
Alright, I have attempted this on both a different browser and a different device. Still seems to not work, for some reason.
<img width="1202" alt="Screenshot 2024-05-31 at 11 27 28 AM" src="https://github.com/rubin-dp0/Support/assets/157167291/92f1463a-b23e-42df-b793-01b6625707a4">

**Comment by MelissaGraham** [comment]
Alright, in the system I can see that your account creation has been started and is at the email confirmation step. I have resent the confirmation email to your @sdsu.edu account. I suspect this is why the system is not allowing the creation of a new account, you already have one, it is just stuck at the email verification step.

**Comment by mochaait** [comment]
@MelissaGraham Perfect! It seems to have worked from there. Awaiting verification now :)

**Comment by MelissaGraham** [comment]
Great @mochaait , I went in and approved your petition, and am going to close this ticket -- but please do open a new one with any new issues you might encounter.
