### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DuhoKim** [rubin-dp0/Support#68]
**Describe the bug**
I cannot Logging On to RSP, getting an error message saying 'SORID "http://cllogon.org/serverE/users/111696 is already associated with CILogon OIDC Claims.'

**To Reproduce**
1. Go to 'https://data.lsst.cloud/'
2. Click on 'Log in'
3. Scroll down to 'ORCID' as Identity Provider
4. Click on 'Log On'
5. Click on 'BEGIN' in the process Self Signup With Approval
6. See error 'SORID "http://cllogon.org/serverE/users/111696 is already associated with CILogon OIDC Claims.'

**Expected behavior**
move on to the next process?

**Screenshots**
![스크린샷 2024-06-13 오후 2 02 35](https://github.com/rubin-dp0/Support/assets/37815561/72f770ea-d88f-4fb1-a920-009b6cf6431a)

**URL**
https://id.lsst.cloud/registry/

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser: chrome
 - Version 126.0.6478.57

**Additional context**
I am assuming the reason has something to do with my previous trial to log on before earning Data Right is conflicting with current Log On process. I believe expunging my account would be a solution similar to Issue #62.

**Comment by MelissaGraham** [comment]
Thanks @DuhoKim, we'll try to get this figured out quickly.

@Frossie, I did some poking around to try and figure out what's happening.

I can see an account for Duho Kim appears under "My Population" with a status of "Pending Approval", but it does not appear under "CO Petitions", where it should, where we would see it and could approve it.

If I go to their page under "My Population" and click "CO Petitions", there isn't one. If I click on "View History", it looks like their account was created on Sep 3 2023, and that neither I nor Heather ever interacted with this account (e.g., it does not appear that we rejected it after not being able to confirm data rights).

Before we expunge the account and ask Duho to start over, can we learning anything about when/why petitions are being lost in the system?

**Comment by DuhoKim** [comment]
Dear @MelissaGraham, I am still having the issue. I want to log on and use it during the tutorial session, which starts today. If you can help with it, I'd appreciate it. Thank you.

**Comment by DuhoKim** [comment]
Dear @MelissaGraham, it seems to be working now. It moved on to email confirmation by input code. But It doesn't progress after I log on again and push begin button on Self Signup With Approval. Should I wait confirmation by a human whether I have Data Right?

**Comment by MelissaGraham** [comment]
Hi @DuhoKim, yes, after the email confirmation step everyone must wait to have their petition approved by a Rubin staff member who verifies data rights. I've just done this for you. You should have received an email about it and be able to log in to the RSP now. Please confirm so we know it worked?

**Comment by DuhoKim** [comment]
Hi @MelissaGraham, I confirm that I can log on to RSP now. I appreciate your help!

**Comment by MelissaGraham** [comment]
Great! Thanks Duho. Closing this issue.
