### ISSUE TITLE
Authentication error RSP

### ISSUE THREAD

**Issue by kh-kr** [rubin-dp0/Support#72]
Hi,

I recently signed up for an RSP account and it has been approved. However, I'm encountering an authentication error when trying to log in using my Gmail and Orchid ID. The error message is visible in the screenshot below:
![Screenshot from 2024-09-14 13-26-03](https://github.com/user-attachments/assets/861416ca-3a57-4a35-93a9-9a198baab2f4)

Could someone please help me understand why I am getting this error and how to resolve it?

Best regards,
Khushboo

**Comment by frossie** [comment]
Khushboo - from what I can see, your account has not actually been approved, it is still showing confirmation. I will reach out to the Community Science Team which is in charge of account approval for more information.

**Comment by jeffcarlin** [comment]
Khushboo has confirmed that they were able to sign in after Frossie reconciled the duplicate accounts in the system. Closing this as solved. (Please let me know if you are still having issues!)
