### ISSUE TITLE
[BUG] Butler errors with Weekly 2022_40 (for DP0.2 tutorial notebook 09ab)

### ISSUE THREAD

**Issue by MelissaGraham** [rubin-dp0/Support#74]
**Describe the bug**
Butler fails to instantiate with Weekly 2022_40, which is the last image DP0.2 tutorial notebooks 09a and 09b ran with. Looking for advice on whether this might be fixable, or whether 09ab has just finally become unsupportable.

**To Reproduce**
1. At data-int (or data), use image Weekly 2022_40, and open tutorial notebook 09a (or 04a).
2. Execute code cells up to and including `butler = Butler('dp02', collections='2.2i/runs/DP0.2')`.
3. Get error message (this is the one from data-int):

```
lsst.daf.butler._butler ERROR: Failed to instantiate Butler from config https://data-int.lsst.cloud/api/butler/repo/dp02/butler.yaml
```

... long traceback [file1_error_data-int_NB09a_w2022_40.txt](https://github.com/user-attachments/files/17383732/file1_error_data-int_NB09a_w2022_40.txt) ... 

```
OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Above is for data-int with NB09a, but similar error messages are returned with 04a and at data.lsst.cloud (all with Weekly 2022_40).

**Desktop (please complete the following information):**
 - OS: macOS 15.0.1
 - Browser: Chrome
 - Version: 129

**Comment by dhirving** [comment]
I think I broke this when I updated the configuration last week to prepare for moving the data to SLAC.  It should fix itself when the data actually moves.  I might be able to tweak the settings in Google Cloud to fix this immediately -- I'll take a look real quick.

The exact error message you showed in this ticket is actually a separate thing, though -- that looks like what you would get if you used `dp02`(-remote) instead of `dp02-direct`.  Apparently because the old Butler version doesn't recognize the new configuration format, it tries to fall back to a default configuration and open a SQLite database.

**Comment by MelissaGraham** [comment]
Thanks David. Yes I was testing first with just 'dp02', but a similar error is returned with 'dp02-direct' at data-int with Weekly 2022_40.

This error does not happen with the recommended image, Weekly 2024_37. And other testing I tried has confirmed that 'dp02' and 'dp02-direct' work as expected at data-int with Weekly 2024_37.

**Comment by dhirving** [comment]
OK I found the problem but I don't have access to fix it.  I put in a request with Dan Speck so hopefully he'll get to it soon.

For posterity the technical details are:

The legacy version of the Butler calls a bucket metadata operation `GetBucketLocation` to check whether the bucket exists on startup.  The buckets used for the DP02 raws, skymaps, and calibs don't have the correct permissions to do this.

We need to add `Storage Legacy Bucket Reader` permission to the GCS account used in the RSP on two buckets:
* curation-us-central1-desc-dc2-run22i
* butler-us-central1-dp01-desc-dr6

**Comment by dhirving** [comment]
https://rubinobs.atlassian.net/browse/DM-46890

**Comment by dhirving** [comment]
I believe this is fixed as of yesterday's patch window.

**Comment by MelissaGraham** [comment]
Yup fixed thank you.
