### ISSUE TITLE
Typically How long does a vera rubin account take to get verified? Thankyou

### ISSUE THREAD

**Issue by coolbros** [rubin-dp0/Support#75]

**Comment by MelissaGraham** [comment]
Hi @coolbros. It should only take a few days to get a response. Check your spam folder for emails with inquiries about your Rubin data rights status. If you don't see any emails after a few days, let us know your name or selected username and we will look into the status of your account.

**Comment by coolbros** [comment]
Hi, have sent you a mail regarding the same . (My email is avarshney@ucsd.edu)

**Comment by MelissaGraham** [comment]
I found your petition in the system and verified it. Thanks Arjun and apologies for the delay. I will close this ticket but do open a new one if anything goes wrong or you can't log in.
