### ISSUE TITLE
[BUG] DP02_13a_Image_Cutout_SciDemo.ipynb does not work on USDF RSP

### ISSUE THREAD

**Issue by mtauraso** [rubin-dp0/Support#76]
**Describe the bug**
Attempting to run the DP02_13a_Image_Cutout_SciDemo.ipynb on USDF RSP at usdf-rsp.slac.stanford.edu results in an unhelpful crash resulting from a 404 of the backend service.

This does not happen on the data.lsst.cloud instance, which leads me to believe it is somehow a USDF issue.

**To Reproduce**
1. Start a Jupyter notebook on the USDF RSP.
2. Upload the [linked notebook
](https://gist.github.com/mtauraso/6666f1fb5c6d9897779ed5c3563bf179)
3. Run the cells individually to see the error in section marked "Error occurs here"
4. Run subsequent cells to see that this is a USDF RSP issue where there is not a repository for the butler URL of sample data.
5. Note that the error does not occur when this sequence of steps is repeated on the cloud RSP at (data.lsst.cloud)
6. Note that similar behavior can be achieved on both RSPs with the `DP02_13a_Image_Cutout_SciDemo.ipynb ` notebook during execution of section 2.2.

**Expected behavior**
I would expect requests for DP0.2 data in tutorial notebooks to be available on the USDF RSP. 

I would separately want the libraries involved to accurately report error conditions. See [pvo issue 625](https://github.com/astropy/pyvo/issues/625) for the issue of accurate reporting of errors.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 132.0

**Additional context**

**Comment by MelissaGraham** [comment]
Hi @mtauraso, thanks for this and apologies for the delayed response. DP0.2 is not supported at the USDF, but is available via the RSP at data.lsst.cloud. The tutorial notebooks will run just fine there. 

For the process to get an account at data.lsst.cloud:
https://rsp.lsst.io/guides/getting-started/get-an-account.html

**Comment by MelissaGraham** [comment]
I think that solves the issue so I'm going to close it but please don't hesitate to reach out again.

**Comment by mtauraso** [comment]
Got it, thanks
